# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'vs2017-win2016'

strategy:
  matrix:
    TsRelease:
      EMBER_TRY_SCENARIO: 'typescript-release'
    # TsBeta:
    #   EMBER_TRY_SCENARIO: 'typescript-beta'
    # EmberRelease:
    #   EMBER_TRY_SCENARIO: 'ember-cli-release'
    # EmberBeta:
    #   EMBER_TRY_SCENARIO: 'ember-cli-beta'

- job: NodeTests
  strategy:
    matrix:
      TsRelease:
        EMBER_TRY_SCENARIO: 'typescript-release'
      # TsBeta:
      #   EMBER_TRY_SCENARIO: 'typescript-beta'

  trigger:
    paths:
      exclude:
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g yarn ember-cli ts-node
    displayName: 'Setup global tools'

  - script: |
      yarn install
      yarn run build
    displayName: 'Build'

  - script: |
      yarn ci:prepare
      yarn test:node
    displayName: 'Node Tests'

- job: EmberTryTests


  trigger:
    paths:
      exclude:
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g yarn ember-cli ts-node
    displayName: 'Setup global tools'

  - script: |
      yarn install
      yarn run build
    displayName: 'Build'

  - script: |
      ls -all
      ember try:one $(EMBER_TRY_SCENARIO) --skip-cleanup
    displayName: 'Test'
