# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'vs2017-win2016'

trigger:
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g yarn ember-cli ts-node mocha
    displayName: 'Setup global tools'

  - script: |
      yarn install
    displayName: 'Build'

  - script: |
      yarn ci:prepare
    displayName: 'Prepare CI environment'

  - script: |
      ember test -r xunit > ember-tests.xml
    displayName: 'Ember App Tests'

  - script: |
      mocha --recursive js/tests -R xunit > node-tests.xml
    displayName: 'Node Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'xUnit'
      testResultsFiles: '*-tests.xml'
