trigger:
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md

jobs:
  - job: example_warning
    steps:
      - script: test "" || echo -e "\043#vso[task.logissue type=warning;] Yikes!!"
  - job: linux_fixed
    displayName: 'linux - fixed dependencies'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure/ci-template.yml
        parameters:
          runLint: true

  - job: commitlint
    displayName: 'conventional commits'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 10.x
      - script: |
          yarn install
          yarn commitlint-azure-pipelines
        displayName: Lint commits

  - job: windows
    displayName: 'windows 10'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: .azure/ci-template.yml
        parameters:
          nodeTestExtraArgs: '--exit'

  - job: linux_floating
    displayName: 'linux - floating dependencies'
    dependsOn: linux_fixed
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: .azure/ci-template.yml
        parameters:
          runLint: true

  - job: ts_versions
    displayName: 'typescript'
    dependsOn: linux_fixed
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        release:
          typeScriptVersion: latest
          allowFailures: false
        beta:
          typeScriptVersion: next
          allowFailures: true
    steps:
      - template: .azure/ci-template.yml
        parameters:
          tsVersion: $(typeScriptVersion)
          allowFailures: $(allowFailures)

  - job: ember_cli_versions
    displayName: 'ember-cli'
    # dependsOn: linux_fixed
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        release:
          eCliVersion: latest
          allowFailures: false
        beta:
          eCliVersion: beta
          allowFailures: true
    steps:
      - template: .azure/ci-template.yml
        parameters:
          emberCliVersion: $(eCliVersion)
          allowFailures: $(allowFailures)
