# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'vs2017-win2016'

strategy:
  matrix:
    TsRelease:
      EMBER_TRY_SCENARIO: 'typescript-release'
    NodeTests:
      EMBER_TRY_SCENARIO: 'node'
    # TsBeta:
    #   EMBER_TRY_SCENARIO: 'typescript-beta'
    # EmberRelease:
    #   EMBER_TRY_SCENARIO: 'ember-cli-release'
    # EmberBeta:
    #   EMBER_TRY_SCENARIO: 'ember-cli-beta'

trigger:
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g yarn ember-cli ts-node
    displayName: 'Setup global tools'

  - script: |
      yarn install
      yarn run build
    displayName: 'Build'

  - script: |
      ls -all
      if [ "$(EMBER_TRY_SCENARIO)" == "node" ];
      then yarn ci:prepare && ls -all && yarn ci:test
      else ember try:one $(EMBER_TRY_SCENARIO);
      fi;

    displayName: 'Test'
